# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes the cumulant tensor for a data matrix.
#'
#' This function calculates the co-kurtosis cumulant tensor for the given input matrix.
#' It uses second-order statistics (covariance) and higher-order tensor computations.
#'
#' @param data A numeric matrix (n x p), where rows are observations and columns are variables.
#' @return A 4-dimensional cumulant tensor (p x p x p x p) as a NumericVector with dimensions assigned.
#'
cumulant_tensor_cpp <- function(data) {
    .Call(`_cokpca_cumulant_tensor_cpp`, data)
}

