#' Tensor Unfolding
#'
#' Unfolds a tensor along specified modes into a matrix.
#'
#' @param K A tensor, typically generated by the `cumulant_tensor_cpp` function.
#' @param row_idx An integer vector specifying dimensions of the tensors to use as the row of the unfolded matrix.
#' @param col_idx An integer vector specifying dimensions of the tensors to use as the column of the unfolded matrix.
#'
#' @return A matrix representing the unfolded tensor.
#'
unfold = function(K, row_idx, col_idx){
  tdim = dim(K)
  perm = c(row_idx, col_idx)
  mat = aperm(K, perm)#rearrage the tensor
  newdims = c(prod(tdim[row_idx]), prod(tdim[col_idx]))
  dim(mat) = newdims
  return(mat)
}



#' Mode-1 Unfolding of a Tensor
#'
#' Unfolds a tensor along the first mode into a matrix.
#'
#' @param K A tensor, typically generated by the `cumulant_tensor_cpp` function.
#'
#' @return A matrix representing the tensor unfolded along the first mode.
#'
mode1unfold = function(K){
  ord = length(dim(K))
  Tm = unfold(K, row_idx = 1, col_idx = 2:ord)
  return(Tm)
}
